In [1]:
import os
import numpy as np
from PIL import Image
from skimage.feature import graycomatrix
from skimage import img_as_ubyte
import shutil


In [2]:
def compute_and_save_glcm(input_folder, output_folder, num_images):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    # Get list of image files from input folder
    image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    
    if len(image_files) < num_images:
        raise ValueError(f"Not enough images in the folder. Found {len(image_files)}, but need {num_images}.")
    
    image_files = image_files[:num_images]
    
    for image_file in image_files:
        image_path = os.path.join(input_folder, image_file)
        # Load image and convert to grayscale
        with Image.open(image_path) as img:
            img_gray = img.convert('L')  # Convert to grayscale
            img_array = np.array(img_gray)
        
        # Compute GLCM
        glcm = graycomatrix(img_array, distances=[1], angles=[0], symmetric=True, normed=True)
        
        # Normalize GLCM values to range [0, 255] for image saving
        glcm_image = img_as_ubyte(np.squeeze(glcm))
        
        # Convert GLCM to an image
        glcm_image = Image.fromarray(glcm_image)
        
        # Save GLCM as PNG image
        glcm_path = os.path.join(output_folder, f"{os.path.splitext(image_file)[0]}_glcm.png")
        glcm_image.save(glcm_path)
    
    print(f"GLCMs saved as PNG images in {output_folder}")

# Compute GLCM for Test Dataset [Size = 400]

In [3]:
# Example usage
input_folder = 'boos_test/cover'
output_folder = 'Test500/boos_test/cover'
num_images = 100

compute_and_save_glcm(input_folder, output_folder, num_images)


GLCMs saved as PNG images in Test500/boos_test/cover


In [4]:
# Example usage
input_folder = 'boos_test/stego'
output_folder = 'Test500/boos_test/stego'
num_images = 100

compute_and_save_glcm(input_folder, output_folder, num_images)


GLCMs saved as PNG images in Test500/boos_test/stego


# Compute GLCM for Train Dataset [Size = 2000]

In [5]:
# Example usage
input_folder = 'boss_train/cover'
output_folder = 'Test500/boss_train/cover'
num_images = 500

compute_and_save_glcm(input_folder, output_folder, num_images)


GLCMs saved as PNG images in Test500/boss_train/cover


In [6]:
# Example usage
input_folder = 'boss_train/stego'
output_folder = 'Test500/boss_train/stego'
num_images = 500

compute_and_save_glcm(input_folder, output_folder, num_images)


GLCMs saved as PNG images in Test500/boss_train/stego


In [11]:
import cv2

In [18]:
img = cv2.imread('Test500/boos_test/stego/9381_glcm.png',0)

In [19]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [20]:
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
np.count_nonzero(img != 0)

114

In [23]:
print(256*256)

65536
